<a href="https://colab.research.google.com/github/ceciliagomez/DeepLearningITBA/blob/master/Revisici%C3%B3n_Conocimiento_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
arr_1 =  np.array([1,2,3,4])
arr_2 = arr_1[:3]
arr_2[0]=10
list_1 = [1,2,3,4]
list_2 =  list_1[:3]
list_2[0]=10
print(list_1, arr_1)

[1, 2, 3, 4] [10  2  3  4]


In [11]:
  arr_1 = np.array([10,  2,  8,  7,  6,  5])
  print(np.argsort(arr_1))

[1 5 4 3 2 0]


In [12]:
arr_1 = np.array([10,  2,  8,  7,  6,  5,  4,  1,  9,  3])
list_1 = [0, 3, 5, -2]
print(arr_1[list_1])

[10  7  5  9]


In [3]:
  arr_1 = np.array([10,  2,  8,  7,  6,  5,  4,  1,  9,  3])
  arr_sorted_1 = arr_1.sort()
  arr_sorted_2 = np.sort(arr_1)
  print(arr_1, arr_sorted_1, arr_sorted_2)

[ 1  2  3  4  5  6  7  8  9 10] None [ 1  2  3  4  5  6  7  8  9 10]


In [27]:
pesos_alturas = np.loadtxt("alturas-pesos.csv", dtype=str, delimiter=',')
print(pesos_alturas[:10])


[['' 'Genero' 'Peso' 'Altura']
 ['7620' 'Mujer' '61.235' '162.40200000000004']
 ['1837' 'Hombre' '97.432' '181.908']
 ['3311' 'Hombre' '73.324' '172.459']
 ['9478' 'Mujer' '55.19300000000001' '157.748']
 ['7805' 'Mujer' '56.886' '151.798']
 ['6737' 'Mujer' '59.834' '158.623']
 ['4413' 'Hombre' '77.618' '172.705']
 ['6018' 'Mujer' '68.889' '169.225']
 ['5165' 'Mujer' '53.874' '155.487']]


In [28]:
pesos_alturas.shape

(8001, 4)

In [30]:
pesos_alturas.dtype

dtype('<U18')

In [31]:
pesos_alturas[1].dtype

dtype('<U18')